# Generated by Django 2.2.8 on 2022-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=15)),
                ('edition', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'bookEntry',
            },
        ),
    ]
